#!/bin/bash

echo "🔐 Setting up App Check Debug Token environment..."
echo ""
echo "To get the App Check debug token to appear:"
echo ""
echo "1. Add this environment variable to your Xcode scheme:"
echo "   - Edit Scheme > Run > Arguments > Environment Variables"
echo "   - Add: FIRDebugEnabled = 1"
echo "   - Add: FIRAppCheckDebugToken = <leave empty>"
echo ""
echo "2. Alternative: Generate a specific debug token:"
echo "   - Add: FIRAppCheckDebugToken = 123a4567-b89c-012d-3456-789012345678"
echo "   (You can use any UUID format string)"
echo ""
echo "3. Clean build folder (Cmd+Shift+K)"
echo "4. Delete app from simulator/device"
echo "5. Build and run again"
echo ""
echo "The token will appear in logs as:"
echo "[Firebase/AppCheck][I-FAA001001] Firebase App Check Debug Token: YOUR-TOKEN-HERE"
echo ""
echo "Once you have the token, add it to Firebase Console:"
echo "1. Go to Firebase Console > App Check"
echo "2. Click on your iOS app"
echo "3. Click menu (3 dots) > Manage debug tokens"
echo "4. Add the token with a descriptive name"