#!/bin/bash

echo "==============================================="
echo "App Store Connect Subscription Setup Checklist"
echo "==============================================="
echo ""

echo "📱 App Information:"
echo "   Bundle ID: com.growthlabs.growthmethod"
echo "   Team ID: 62T6J77P6R"
echo "   App ID: 6748406423"
echo ""

echo "✅ Required Product IDs to Create:"
echo "   1. com.growthlabs.growthmethod.subscription.premium.weekly"
echo "   2. com.growthlabs.growthmethod.subscription.premium.quarterly"
echo "   3. com.growthlabs.growthmethod.subscription.premium.yearly"
echo ""

echo "📋 Quick Setup Guide:"
echo ""
echo "1. Open App Store Connect:"
echo "   https://appstoreconnect.apple.com"
echo ""
echo "2. Navigate to:"
echo "   My Apps → Growth: Method → Features → In-App Purchases"
echo ""
echo "3. Create THREE auto-renewable subscriptions with:"
echo "   - Weekly: \$4.99 (1 Week duration)"
echo "   - Quarterly: \$29.99 (3 Months duration)"
echo "   - Yearly: \$49.99 (1 Year duration)"
echo ""
echo "4. Create subscription group:"
echo "   Name: 'Growth: Method Pro'"
echo ""
echo "5. Required for each product:"
echo "   ✓ Localization (at least English)"
echo "   ✓ Display Name"
echo "   ✓ Description"
echo "   ✓ Screenshot (1242x2208 minimum)"
echo ""
echo "6. Mark products as 'Ready to Submit'"
echo ""

echo "⏱️  Timeline:"
echo "   - Setup time: ~30 minutes"
echo "   - Propagation: 2-24 hours"
echo "   - TestFlight availability: After propagation"
echo ""

echo "🧪 Testing Options While Waiting:"
echo "   1. Use iOS Simulator (products load from local config)"
echo "   2. App shows fallback message on device"
echo "   3. Retry button available in paywall"
echo ""

echo "📞 Support:"
echo "   If products don't appear after 24 hours:"
echo "   - Check Paid Applications Agreement is active"
echo "   - Verify banking information is complete"
echo "   - Ensure tax forms are submitted"
echo ""

echo "🔗 Direct Links:"
echo "   App Store Connect: https://appstoreconnect.apple.com"
echo "   In-App Purchases: https://appstoreconnect.apple.com/apps/6748406423/features/iap"
echo "   Agreements: https://appstoreconnect.apple.com/agreements"
echo ""

echo "==============================================="
echo "Once products are created, wait 2-24 hours"
echo "Then test in TestFlight or on device"
echo "==============================================="