#!/bin/bash

echo "✅ FINAL ARCHIVE CHECKLIST"
echo "========================="
echo ""
echo "✓ All build artifacts cleaned"
echo "✓ Automatic signing enabled for both targets"
echo "✓ Bundle IDs corrected:"
echo "  - App (Release): com.growthlabs.growthmethod ✅"
echo "  - Widget (Release): com.growthlabs.growthmethod.GrowthTimerWidget ✅"
echo "✓ Development Team: 62T6J77P6R (Growth Labs, Inc)"
echo "✓ App exists in App Store Connect (ID: 6748406423)"
echo ""
echo "🎯 ARCHIVE INSTRUCTIONS:"
echo "========================"
echo ""
echo "1. Open Xcode"
echo ""
echo "2. IMPORTANT: Check your Apple ID:"
echo "   → Xcode → Settings → Accounts"
echo "   → Make sure you're signed in"
echo "   → If issues, remove and re-add your Apple ID"
echo ""
echo "3. Select destination:"
echo "   → In the toolbar, change from simulator to 'Any iOS Device (arm64)'"
echo ""
echo "4. Clean and Archive:"
echo "   → Product → Clean Build Folder (Shift+Cmd+K)"
echo "   → Product → Archive"
echo "   → Wait for completion (may take 5-10 minutes)"
echo ""
echo "5. In the Organizer window:"
echo "   → Select your archive"
echo "   → Click 'Distribute App'"
echo "   → You should see:"
echo "     • App Store Connect ← Select this"
echo "     • TestFlight Internal Only"
echo "     • Custom"
echo ""
echo "6. Follow the wizard:"
echo "   → Choose 'Upload' (or 'Export' for later)"
echo "   → Let Xcode manage signing"
echo "   → Upload to App Store Connect"
echo ""
echo "🚨 IF YOU STILL ONLY SEE 'CUSTOM':"
echo "==================================="
echo "This means one of these issues:"
echo ""
echo "1. Account permissions:"
echo "   → Go to https://appstoreconnect.apple.com/access/users"
echo "   → Verify you have 'Admin' or 'App Manager' role"
echo "   → If not, ask your team admin to upgrade your role"
echo ""
echo "2. Team membership:"
echo "   → Go to https://developer.apple.com/account"
echo "   → Verify your team membership is active"
echo "   → Check that it's not expired"
echo ""
echo "3. Xcode account issue:"
echo "   → Sign out completely from Xcode"
echo "   → Quit Xcode"
echo "   → Delete ~/Library/Developer/Xcode/DerivedData/"
echo "   → Reopen Xcode and sign in again"
echo ""
echo "Ready to archive! Good luck! 🚀"