#!/bin/bash

echo "🔐 App Check Token Registration Helper"
echo "====================================="
echo ""

# The token that needs to be registered
TOKEN="DC769389-3431-4556-A9BB-44B79AF64E65"

echo "📋 Token to register: $TOKEN"
echo ""
echo "⚠️  MANUAL STEPS REQUIRED:"
echo ""
echo "1. Open Firebase Console:"
echo "   https://console.firebase.google.com/project/growth-70a85/appcheck/apps"
echo ""
echo "2. Click on your iOS app (com.growthlabs.growthmethod)"
echo ""
echo "3. Click the '⋮' (three dots) menu → 'Manage debug tokens'"
echo ""
echo "4. Click 'Add debug token'"
echo ""
echo "5. Paste this token: $TOKEN"
echo ""
echo "6. Give it a descriptive name like:"
echo "   - 'iOS Dev Device - $(date +%Y-%m-%d)'"
echo "   - 'Xcode Simulator'"
echo "   - 'Development Build'"
echo ""
echo "7. Click 'Done'"
echo ""
echo "✅ After registration:"
echo "   - Clean build in Xcode (Cmd+Shift+K)"
echo "   - Run the app again"
echo "   - The 403 errors should disappear"
echo ""
echo "🔍 To verify it's working:"
echo "   - Check Xcode console for no more 403 errors"
echo "   - Firebase Functions should work properly"
echo ""
echo "📊 Alternative: Use the new App Check Diagnostics"
echo "   Settings → Developer Tools → App Check Diagnostics"