#!/bin/bash

echo "🚀 Deploying Angion Methods to Firebase..."
echo ""
echo "This script will update the following methods in Firestore:"
echo "  - Angion Method 1.0"
echo "  - Angio Pumping"
echo "  - Angion Method 2.0"
echo "  - Jelq 2.0"
echo "  - Vascion"
echo ""
echo "⚠️  IMPORTANT: This requires manual steps:"
echo ""
echo "1. Open Firebase Console: https://console.firebase.google.com/project/growth-70a85/firestore/data/~2FgrowthMethods"
echo ""
echo "2. For each method, click on the document ID and update with the JSON data from:"
echo "   - angion_method_1_0: scripts/angion-method-1-0-multistep.json"
echo "   - angio_pumping: scripts/angion-methods-multistep/angio-pumping.json"
echo "   - angion_method_2_0: scripts/angion-methods-multistep/angion-method-2-0.json"
echo "   - jelq_2_0: scripts/angion-methods-multistep/jelq-2-0.json"
echo "   - vascion: scripts/angion-methods-multistep/vascion.json"
echo ""
echo "3. When updating, preserve these fields from the existing documents:"
echo "   - createdAt"
echo "   - viewCount"
echo "   - averageRating"
echo "   - totalRatings"
echo ""
echo "4. Add/update these fields:"
echo "   - updatedAt: (current timestamp)"
echo "   - hasMultipleSteps: true"
echo "   - isActive: true"
echo ""
echo "Opening the first JSON file for you to copy..."
echo ""

# Display the first method for easy copying
echo "===== ANGION METHOD 1.0 JSON ====="
cat scripts/angion-method-1-0-multistep.json | jq .
echo ""
echo "Copy the above JSON and update the 'angion_method_1_0' document in Firestore."
echo ""
echo "To view other methods, run:"
echo "  cat scripts/angion-methods-multistep/angio-pumping.json | jq ."
echo "  cat scripts/angion-methods-multistep/angion-method-2-0.json | jq ."
echo "  cat scripts/angion-methods-multistep/jelq-2-0.json | jq ."
echo "  cat scripts/angion-methods-multistep/vascion.json | jq ."